# [PSEUDO-STUB] Fallback for fixed_commands.py (stubgen failed)
class FixedCommandRegistry(IFixedCommandRegistry):
    ...
    def __init__(self):
        ...
    def register(self, command: ICommand) -> None:
        ...
    def get_command(self, name: str) -> Optional[ICommand]:
        ...
    def list_commands(self) -> List[str]:
        ...
    def has_command(self, name: str) -> bool:
        ...
def bootstrap_fixed_registry(registry: IFixedCommandRegistry):
    ...