from dataclasses import asdict
import json
import os
import logging
from datetime import datetime
import traceback
from pathlib import Path
from typing import Optional, Any

from simulation.dtos.watchtower import WatchtowerSnapshotDTO

logger = logging.getLogger(__name__)

class PersistenceBridge:
    """
    Handles automated local persistence of simulation snapshots.
    Ensures that web-streamed data is also archived locally (Double-Track).
    """
    
    def __init__(self, simulation: Optional[Any] = None, base_dir: str = "reports/snapshots"):
        self.simulation = simulation
        self.base_dir = Path(base_dir)
        self.base_dir.mkdir(parents=True, exist_ok=True)
        self._last_saved_tick = -1

    def save_snapshot(self, snapshot: WatchtowerSnapshotDTO, interval: int = 1):
        """
        Saves the DTO to a local JSON file at specified tick intervals.
        """
        if snapshot.tick % interval != 0 or snapshot.tick == self._last_saved_tick:
            return

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"snapshot_tick_{snapshot.tick:05d}_{timestamp}.json"
        target_path = self.base_dir / filename

        try:
            # Convert DTO to dict (dataclasses.asdict is expensive, manual is faster for simple structures)
            # But for deep nesting, asdict is safer.
            data = asdict(snapshot)

            with open(target_path, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
            
            self._last_saved_tick = snapshot.tick
            logger.info(f"✅ [Persistence] Saved local snapshot: {filename}")
            
            # Generate MD Executive Summary for milestones
            if snapshot.tick % 100 == 0:
                self._generate_executive_summary(snapshot, timestamp)

        except Exception as e:
            traceback.print_exc()
            logger.error(f"❌ [Persistence] Failed to save snapshot: {e}")

    def _generate_executive_summary(self, snapshot: WatchtowerSnapshotDTO, timestamp: str):
        """Generates a human-readable Markdown summary of the economy."""
        filename = f"executive_summary_tick_{snapshot.tick:05d}_{timestamp}.md"
        target_path = self.base_dir / filename
        
        # Attribute access for refactored DTO
        macro = snapshot.macro
        finance = snapshot.finance
        f_supply = finance.supply
        f_rates = finance.rates
        politics = snapshot.politics
        p_status = politics.status
        p_approval = politics.approval
        integrity = snapshot.integrity

        content = f"""# Watchtower Executive Summary [Tick {snapshot.tick}]
Date: {datetime.now().isoformat()}

## 📊 Vitals
- **GDP**: {macro.gdp:,.2f}
- **CPI**: {macro.cpi:,.2f}
- **Unemployment**: {macro.unemploy:.2f}%
- **Gini**: {macro.gini:.4f}

## 💸 Monetary & Finance
- **M2 Supply**: {f_supply.m2:,.2f}
- **Base Rate**: {f_rates.base:.2f}%
- **Integrity (Leak)**: {integrity.m2_leak:.4f}

## 🏛️ Politics & Status
- **Ruling Party**: {p_status.ruling_party}
- **Approval**: {p_approval.total * 100:.1f}%
- **Social Cohesion**: {p_status.cohesion * 100:.1f}%

---
*This report was auto-generated by the PersistenceBridge.*
"""
        with open(target_path, "w", encoding="utf-8") as f:
            f.write(content)
        logger.info(f"📜 [Persistence] Generated executive summary: {filename}")
