import logging
from _typeshed import Incomplete
from modules.common.interfaces import IPropertyOwner as IPropertyOwner, IResident as IResident
from modules.finance.api import LienDTO as LienDTO
from modules.housing.api import IHousingService as IHousingService
from modules.inventory.api import IInventoryHandler as IInventoryHandler
from simulation.core_agents import Household as Household
from simulation.dtos.api import SimulationState as SimulationState
from simulation.models import Transaction as Transaction
from typing import Any
from uuid import UUID

logger: Incomplete

class HousingService(IHousingService):
    logger: Incomplete
    contract_locks: dict[int, UUID]
    real_estate_units: list[Any]
    def __init__(self, logger: logging.Logger | None = None) -> None: ...
    def set_real_estate_units(self, units: list[Any]) -> None: ...
    def is_under_contract(self, property_id: int) -> bool: ...
    def set_under_contract(self, property_id: int, saga_id: UUID) -> bool: ...
    def release_contract(self, property_id: int, saga_id: UUID) -> bool: ...
    def lock_asset(self, asset_id: Any, lock_owner_id: Any) -> bool: ...
    def release_asset(self, asset_id: Any, lock_owner_id: Any) -> bool: ...
    def transfer_asset(self, asset_id: Any, new_owner_id: Any) -> bool: ...
    def add_lien(self, property_id: int, loan_id: Any, lienholder_id: int | None = None, principal: int | None = None) -> str | None: ...
    def remove_lien(self, property_id: int, lien_id: str) -> bool: ...
    def transfer_ownership(self, property_id: int, new_owner_id: int) -> bool: ...
    def process_transaction(self, tx: Transaction, state: SimulationState) -> None: ...
