# --- Simulation Parameters ---
NUM_HOUSEHOLDS = 20
NUM_FIRMS = 4
SIMULATION_TICKS = 100

# --- Initial Agent Configuration ---
INITIAL_HOUSEHOLD_ASSETS_MEAN = 50.0
INITIAL_HOUSEHOLD_ASSETS_RANGE = 0.2
INITIAL_HOUSEHOLD_LIQUIDITY_NEED_MEAN = 50.0
INITIAL_HOUSEHOLD_LIQUIDITY_NEED_RANGE = 0.2
INITIAL_HOUSEHOLD_NEEDS_MEAN = {
    "survival_need": 30.0,
    "recognition_need": 20.0,
    "growth_need": 10.0,
    "wealth_need": 10.0,
    "imitation_need": 15.0,
    "labor_need": 0.0,
    "child_rearing_need": 0.0
}
INITIAL_HOUSEHOLD_NEEDS_RANGE = 0.1
INITIAL_EMPLOYMENT_RATE = 0.5 # 초기 고용률

INITIAL_FIRM_CAPITAL_MEAN = 10000.0
INITIAL_FIRM_CAPITAL_RANGE = 0.2
INITIAL_FIRM_LIQUIDITY_NEED_MEAN = 200.0
INITIAL_FIRM_LIQUIDITY_NEED_RANGE = 0.2
INITIAL_FIRM_INVENTORY_MEAN = 100.0
INITIAL_FIRM_INVENTORY_RANGE = 0.2
FIRM_PRODUCTIVITY_FACTOR = 1.0
FIRM_PRODUCTION_TARGETS = {"food": 200, "luxury_food": 40}

# --- Value Orientations (as strings) ---
VALUE_ORIENTATION_WEALTH_AND_NEEDS = "wealth_and_needs"
VALUE_ORIENTATION_NEEDS_AND_GROWTH = "needs_and_growth"
VALUE_ORIENTATION_NEEDS_AND_SOCIAL_STATUS = "needs_and_social_status"

# --- Market & Decision Logic ---
GOODS_MARKET_SELL_PRICE = 5.0
INITIAL_WAGE = 10.0 # Renamed from LABOR_MARKET_OFFERED_WAGE
BASE_WAGE = 10.0
WAGE_INFLATION_ADJUSTMENT_FACTOR = 0.1
LABOR_MARKET_MIN_WAGE = 8.0
HOUSEHOLD_MIN_WAGE_DEMAND = 10.0
HOUSEHOLD_RESERVATION_PRICE_BASE = 5.0
HOUSEHOLD_NEED_PRICE_MULTIPLIER = 1.0
HOUSEHOLD_ASSET_PRICE_MULTIPLIER = 0.1
HOUSEHOLD_PRICE_ELASTICITY_FACTOR = 0.5
HOUSEHOLD_STOCKPILING_BONUS_FACTOR = 0.2
MIN_SELL_PRICE = 1.0
MAX_SELL_PRICE = 100.0
MAX_SELL_QUANTITY = 50.0
PERCEIVED_PRICE_UPDATE_FACTOR = 0.1
INVENTORY_HOLDING_COST_RATE = 0.005
DIVIDEND_RATE = 0.1
WAGE_DECAY_RATE = 0.9
RND_WAGE_PREMIUM = 1.5
WAGE_COMPETITION_PREMIUM = 0.05

# --- Production & Stock ---
OVERSTOCK_THRESHOLD = 1.2
UNDERSTOCK_THRESHOLD = 0.8
FIRM_MIN_EMPLOYEES = 1
FIRM_MAX_EMPLOYEES = 50
FIRM_MIN_PRODUCTION_TARGET = 10.0
FIRM_MAX_PRODUCTION_TARGET = 500.0
PRODUCTION_ADJUSTMENT_FACTOR = 0.1
PRICE_ADJUSTMENT_FACTOR = 0.05
PRICE_ADJUSTMENT_EXPONENT = 1.2

# --- Need Dynamics & Thresholds ---
SURVIVAL_NEED_INCREASE_RATE = 1.0
RECOGNITION_NEED_INCREASE_RATE = 0.5
GROWTH_NEED_INCREASE_RATE = 0.3
LIQUIDITY_NEED_INCREASE_RATE = 0.2
WEALTH_NEED_INCREASE_RATE = 0.1
IMITATION_NEED_INCREASE_RATE = 0.4
CHILD_REARING_NEED_INCREASE_RATE = 0.1
SURVIVAL_NEED_THRESHOLD = 20.0
LABOR_NEED_THRESHOLD = 50.0
GROWTH_NEED_THRESHOLD = 60.0
IMITATION_NEED_THRESHOLD = 70.0
CHILD_REARING_NEED_THRESHOLD = 80.0
RECOGNITION_NEED_THRESHOLD = 40.0
WEALTH_NEED_THRESHOLD = 70.0
NEED_MEDIUM_THRESHOLD = 50.0
NEED_HIGH_THRESHOLD = 80.0
SURVIVAL_TO_LABOR_NEED_FACTOR = 0.5

# --- Agent Lifecycle & Death ---
SURVIVAL_NEED_DEATH_THRESHOLD = 100.0
ASSETS_DEATH_THRESHOLD = 0.0
HOUSEHOLD_DEATH_TURNS_THRESHOLD = 4
ASSETS_CLOSURE_THRESHOLD = 0.0
FIRM_CLOSURE_TURNS_THRESHOLD = 4

# --- Social & Lifecycle & AI ---
SOCIAL_STATUS_ASSET_WEIGHT = 0.3
SOCIAL_STATUS_LUXURY_WEIGHT = 0.7
INITIAL_CHILD_ASSETS_FACTOR = 0.5
RND_PRODUCTIVITY_MULTIPLIER = 0.01
AI_SKILL_REWARD_WEIGHT = 10.0
AI_ASSET_REWARD_WEIGHT = 1.0
AI_SOCIAL_STATUS_REWARD_WEIGHT = 5.0
THRESHOLD_FORCED_LABOR_EXPLORATION = 1.0
FORCED_LABOR_WAGE_FACTOR = 0.8
HOUSEHOLD_ASSETS_THRESHOLD_FOR_LABOR_SUPPLY = 1.0
FORCED_LABOR_EXPLORATION_PROBABILITY = 0.5
IMITATION_ASSET_THRESHOLD = 500.0
CHILD_REARING_ASSET_THRESHOLD = 1000.0
SURVIVAL_NEED_THRESHOLD_FOR_OTHER_ACTIONS = 30.0
ASSETS_THRESHOLD_FOR_OTHER_ACTIONS = 200.0

# --- Loan Market ---
LOAN_INTEREST_RATE = 0.05
INITIAL_BANK_ASSETS = 1000000.0
HOUSEHOLD_LOAN_THRESHOLD = 500.0
LOAN_DURATION = 20
DEFAULT_LOAN_DURATION = 10

# --- Liquidity ---
LIQUIDITY_RATIO_MAX = 0.8
LIQUIDITY_RATIO_MIN = 0.1
LIQUIDITY_RATIO_DIVISOR = 100.0

# --- Logging ---
ROOT_LOGGER_LEVEL = "INFO"
