from enum import Enum

class Intention(Enum):
    """
    AI 에이전트의 최상위 목표를 나타내는 Enum.
    가계와 기업 모두에게 적용될 수 있는 공용 목표와 각자에게 특화된 목표를 포함한다.
    """
    DO_NOTHING = ...
    INCREASE_ASSETS = ...
    SATISFY_SURVIVAL_NEED = ...
    SATISFY_SOCIAL_NEED = ...
    IMPROVE_SKILLS = ...
    MAXIMIZE_PROFIT = ...
    INCREASE_MARKET_SHARE = ...
    IMPROVE_PRODUCTIVITY = ...

class Tactic(Enum):
    """
    Intention을 달성하기 위한 구체적인 행동 방침을 나타내는 Enum.
    """
    DO_NOTHING = ...
    NO_ACTION = ...
    WAIT = ...
    EVALUATE_CONSUMPTION_OPTIONS = ...
    BUY_FOR_BUFFER = ...
    BUY_BASIC_FOOD = ...
    BUY_LUXURY_FOOD = ...
    DO_NOTHING_CONSUMPTION = ...
    PARTICIPATE_LABOR_MARKET = ...
    INVEST_IN_STOCKS = ...
    START_BUSINESS = ...
    TAKE_EDUCATION = ...
    ADJUST_PRICE = ...
    ADJUST_PRODUCTION = ...
    ADJUST_WAGES = ...
    PRICE_INCREASE_SMALL = ...
    PRICE_INCREASE_MEDIUM = ...
    PRICE_DECREASE_SMALL = ...
    PRICE_DECREASE_MEDIUM = ...
    PRICE_HOLD = ...
    LOWER_PRICE = ...
    INCREASE_MARKETING = ...
    INVEST_IN_CAPITAL = ...
    TRAIN_EMPLOYEES = ...

class Personality(Enum):
    """
    AI 에이전트의 고유한 특질(성격)을 나타내는 Enum.
    각 특질은 특정 Intention에 대한 욕구 성장 가중치에 영향을 미친다.
    """
    MISER = ...
    STATUS_SEEKER = ...
    GROWTH_ORIENTED = ...
    IMPULSIVE = ...
    CONSERVATIVE = ...
    BALANCED = ...
    GROWTH_HACKER = ...
    CASH_COW = ...

class Aggressiveness(Enum):
    """
    AI 에이전트 행동의 적극성을 나타내는 Enum.
    """
    PASSIVE = ...
    NORMAL = ...
    NEUTRAL = ...
    AGGRESSIVE = ...

class PoliticalParty(Enum):
    """
    Phase 17-5: Leviathan
    Political Parties with distinct policy biases.
    """
    BLUE = ...
    RED = ...

class EconomicSchool(Enum):
    """
    Phase 4: Political Economy
    Economic schools for government advisors.
    """
    KEYNESIAN = ...
    MONETARIST = ...
    AUSTRIAN = ...

class PoliticalVision(Enum):
    """
    Phase 4: Political Economy
    Household ideological preference.
    """
    GROWTH = ...
    SAFETY = ...

class PolicyActionTag(Enum):
    """
    Phase 4: Political Economy
    Tags for government actions to manage lockouts and accountability.
    """
    KEYNESIAN_FISCAL = ...
    AUSTRIAN_AUSTERITY = ...
    MONETARIST_RULES = ...
    GENERAL_ADMIN = ...
    SOCIAL_POLICY = ...
    FIRM_BAILOUT = ...
    INFRASTRUCTURE_INVESTMENT = ...
