import logging
from _typeshed import Incomplete
from modules.finance.api import IShareholderRegistry as IShareholderRegistry, ITaxService as ITaxService
from modules.household.api import IHouseholdFactory as IHouseholdFactory
from modules.hr.api import IHRService as IHRService
from modules.simulation.api import IEstateRegistry as IEstateRegistry
from modules.system.api import IAgentRegistry as IAgentRegistry, IAssetRecoverySystem as IAssetRecoverySystem
from simulation.ai.vectorized_planner import VectorizedHouseholdPlanner as VectorizedHouseholdPlanner
from simulation.dtos.api import SimulationState as SimulationState
from simulation.finance.api import ISettlementSystem as ISettlementSystem
from simulation.models import Transaction as Transaction
from simulation.systems.api import AgentLifecycleManagerInterface as AgentLifecycleManagerInterface
from simulation.systems.demographic_manager import DemographicManager as DemographicManager
from simulation.systems.firm_management import FirmSystem as FirmSystem
from simulation.systems.immigration_manager import ImmigrationManager as ImmigrationManager
from simulation.systems.inheritance_manager import InheritanceManager as InheritanceManager
from simulation.systems.lifecycle.aging_system import AgingSystem as AgingSystem
from simulation.systems.lifecycle.api import BirthConfigDTO as BirthConfigDTO, DeathConfigDTO as DeathConfigDTO, LifecycleConfigDTO as LifecycleConfigDTO
from simulation.systems.lifecycle.birth_system import BirthSystem as BirthSystem
from simulation.systems.lifecycle.death_system import DeathSystem as DeathSystem
from simulation.systems.lifecycle.marriage_system import MarriageSystem as MarriageSystem
from simulation.systems.liquidation_manager import LiquidationManager as LiquidationManager
from typing import Any

class AgentLifecycleManager(AgentLifecycleManagerInterface):
    """
    Handles agent creation, aging, death, and liquidation.
    WO-103: Implements SystemInterface.
    WO-109: Returns transactions for deferred execution (Sacred Sequence).
    """
    config: Incomplete
    logger: Incomplete
    agent_registry: Incomplete
    hr_service: Incomplete
    tax_service: Incomplete
    liquidation_manager: Incomplete
    aging_system: Incomplete
    birth_system: Incomplete
    death_system: Incomplete
    marriage_system: Incomplete
    def __init__(self, config_module: Any, demographic_manager: DemographicManager, inheritance_manager: InheritanceManager, firm_system: FirmSystem, settlement_system: ISettlementSystem, public_manager: IAssetRecoverySystem, logger: logging.Logger, shareholder_registry: IShareholderRegistry = None, household_factory: IHouseholdFactory | None = None, hr_service: IHRService | None = None, tax_service: ITaxService | None = None, agent_registry: IAgentRegistry | None = None, estate_registry: IEstateRegistry | None = None) -> None: ...
    def reset_agents_tick_state(self, state: SimulationState) -> None:
        """
        Calls the reset method on all active agents at the end of a tick.
        """
    def execute(self, state: SimulationState) -> list[Transaction]:
        """
        Processes lifecycle events for the tick.
        Returns:
            List[Transaction]: Transactions generated by lifecycle events (e.g., inheritance)
                                to be queued for the NEXT tick.
        """
