from _typeshed import Incomplete
from dataclasses import dataclass, field
from modules.hr.api import IEmployeeDataProvider as IEmployeeDataProvider
from modules.system.api import CurrencyCode as CurrencyCode
from typing import Any, Deque

@dataclass
class HRState:
    """State for HR operations."""
    employees: list[IEmployeeDataProvider] = field(default_factory=list)
    employee_wages: dict[int, int] = field(default_factory=dict)
    employees_data: dict[int, dict[str, Any]] = field(default_factory=dict)
    unpaid_wages: dict[int, list[tuple[int, int]]] = field(default_factory=dict)
    hires_this_tick: int = ...
    hires_prev_tick: int = ...
    target_hires_this_tick: int = ...
    target_hires_prev_tick: int = ...
    wage_offer_this_tick: int = ...
    wage_offer_prev_tick: int = ...
    @property
    def hires_last_tick(self) -> int:
        """Deprecated alias for backward compatibility."""
    @hires_last_tick.setter
    def hires_last_tick(self, value: int): ...

@dataclass
class FinanceState:
    """
    State for Finance operations.
    MIGRATION: All monetary values are now integers (pennies).
    """
    retained_earnings_pennies: int = ...
    dividends_paid_last_tick_pennies: int = ...
    consecutive_loss_turns: int = ...
    current_profit: dict[CurrencyCode, int] = field(default_factory=Incomplete)
    revenue_this_turn: dict[CurrencyCode, int] = field(default_factory=Incomplete)
    cost_this_turn: dict[CurrencyCode, int] = field(default_factory=Incomplete)
    revenue_this_tick: dict[CurrencyCode, int] = field(default_factory=Incomplete)
    expenses_this_tick: dict[CurrencyCode, int] = field(default_factory=Incomplete)
    profit_history: Deque[int] = field(default_factory=Incomplete)
    last_revenue_pennies: int = ...
    last_marketing_spend_pennies: int = ...
    last_daily_expenses_pennies: int = ...
    last_sales_volume: float = ...
    sales_volume_this_tick: float = ...
    is_distressed: bool = ...
    distress_tick_counter: int = ...
    total_debt_pennies: int = ...
    average_interest_rate: float = ...
    total_shares: float = ...
    treasury_shares: float = ...
    dividend_rate: float = ...
    valuation_pennies: int = ...
    has_bailout_loan: bool = ...
    is_bankrupt: bool = ...
    owned_properties: list[int] = field(default_factory=list)
    is_publicly_traded: bool = ...
    founder_id: int | None = ...
    def reset_tick_counters(self, primary_currency: CurrencyCode):
        """Resets tick-specific counters."""

@dataclass
class ProductionState:
    """State for Production operations."""
    capital_stock: int = ...
    production_target: float = ...
    current_production: float = ...
    productivity_factor: float = ...
    automation_level: float = ...
    base_quality: float = ...
    inventory_quality: dict[str, float] = field(default_factory=dict)
    research_history: dict[str, Any] = field(default_factory=Incomplete)
    sector: str = ...
    specialization: str = ...

@dataclass
class SalesState:
    """State for Sales operations."""
    marketing_budget: float = ...
    marketing_budget_pennies: int = ...
    marketing_budget_rate: float = ...
    prev_awareness: float = ...
    adstock: float = ...
    brand_awareness: float = ...
    perceived_quality: float = ...
    last_prices: dict[str, int] = field(default_factory=dict)
    inventory_last_sale_tick: dict[str, int] = field(default_factory=dict)
    prev_market_share: float = ...
    prev_assets: float = ...
    prev_avg_quality: float = ...
