from .api import CurrencyCode as CurrencyCode, DEFAULT_CURRENCY as DEFAULT_CURRENCY, IWallet as IWallet, WalletOpLogDTO as WalletOpLogDTO
from .audit import GLOBAL_WALLET_LOG as GLOBAL_WALLET_LOG
from _typeshed import Incomplete
from modules.common.financial.dtos import MoneyDTO as MoneyDTO
from modules.finance.api import InsufficientFundsError as InsufficientFundsError

class Wallet(IWallet):
    """
    An encapsulated, auditable container for an agent's multi-currency assets.
    MIGRATION: Stores all values as integers (pennies).
    """
    owner_id: Incomplete
    allow_negative_balance: Incomplete
    def __init__(self, owner_id: int, initial_balances: dict[CurrencyCode, int] | None = None, audit_log: list[WalletOpLogDTO] | None = None, allow_negative_balance: bool = False) -> None: ...
    def get_balance(self, currency: CurrencyCode = ...) -> int: ...
    def get_all_balances(self) -> dict[CurrencyCode, int]: ...
    def load_balances(self, balances: dict[CurrencyCode, int]) -> None:
        """
        Replaces current balances with the provided dictionary.
        Used for state hydration/loading.
        """
    def add(self, amount: int, currency: CurrencyCode = ..., memo: str = '', tick: int = -1) -> None: ...
    def subtract(self, amount: int, currency: CurrencyCode = ..., memo: str = '', tick: int = -1) -> None: ...
    def __add__(self, other: IWallet) -> IWallet: ...
    def __sub__(self, other: IWallet) -> IWallet: ...
    def __iadd__(self, other: IWallet) -> IWallet: ...
    def __isub__(self, other: IWallet) -> IWallet: ...
