from _typeshed import Incomplete
from modules.common.protocol import enforce_purity as enforce_purity
from modules.simulation.api import IInventoryHandler as IInventoryHandler, InventorySlot as InventorySlot

logger: Incomplete

class InventoryManager(IInventoryHandler):
    """
    Component for managing inventory with quality tracking.
    Composition replacement for BaseAgent inventory logic.
    """
    owner_id: Incomplete
    def __init__(self, owner_id: int, inventory: dict[str, float] | None = None, quality: dict[str, float] | None = None) -> None: ...
    def add_item(self, item_id: str, quantity: float, transaction_id: str | None = None, quality: float = 1.0, slot: InventorySlot = ...) -> bool: ...
    def remove_item(self, item_id: str, quantity: float, transaction_id: str | None = None, slot: InventorySlot = ...) -> bool: ...
    def get_quantity(self, item_id: str, slot: InventorySlot = ...) -> float: ...
    def get_quality(self, item_id: str, slot: InventorySlot = ...) -> float: ...
    def get_all_items(self, slot: InventorySlot = ...) -> dict[str, float]: ...
    def clear_inventory(self, slot: InventorySlot = ...) -> None: ...
