from modules.scenarios.api import Category as Category, IJudgeFactory as IJudgeFactory, IScenarioJudge as IScenarioJudge, ScenarioStrategy as ScenarioStrategy, Tier as Tier
from modules.system.api import DEFAULT_CURRENCY as DEFAULT_CURRENCY, IWorldState as IWorldState
from typing import Any

class GoldStandardJudge:
    def __init__(self) -> None: ...
    @property
    def tier(self) -> Tier: ...
    @property
    def name(self) -> str: ...
    def judge(self, world_state: IWorldState) -> bool: ...
    def get_metrics(self, world_state: IWorldState) -> dict[str, Any]: ...

class IndustrialRevolutionJudge:
    def __init__(self) -> None: ...
    @property
    def tier(self) -> Tier: ...
    @property
    def name(self) -> str: ...
    def judge(self, world_state: IWorldState) -> bool: ...
    def get_metrics(self, world_state: IWorldState) -> dict[str, Any]: ...

class DomainJudgeFactory(IJudgeFactory):
    def create_judges(self, strategy: ScenarioStrategy) -> list[IScenarioJudge]: ...
