from _typeshed import Incomplete

IS_PYDANTIC_MOCKED: Incomplete

class TestGlobalRegistry:
    def test_basic_set_get(self) -> None: ...
    def test_locking_mechanism(self) -> None: ...
    def test_migrate_from_dict(self) -> None: ...
    def test_reset_to_defaults(self) -> None: ...
    def test_delete_layer(self) -> None: ...
    def test_snapshot_returns_pydantic(self) -> None: ...
    def test_watchtower_dto_serialization(self) -> None: ...
    def test_cockpit_command_validation(self) -> None: ...
