import pytest
from modules.system.api import AgentBankruptcyEventDTO as AgentBankruptcyEventDTO

class TestPublicManager:
    @pytest.fixture
    def public_manager(self): ...
    def test_process_bankruptcy_event(self, public_manager) -> None: ...
    def test_generate_liquidation_orders(self, public_manager) -> None: ...
    def test_confirm_sale(self, public_manager) -> None: ...
    def test_deposit_revenue(self, public_manager) -> None: ...
    def test_generate_liquidation_orders_no_signal(self, public_manager) -> None: ...
    def test_generate_liquidation_orders_resets_metrics(self, public_manager) -> None: ...
    def test_execute_asset_buyout(self, public_manager) -> None: ...
