"""
Constants for Government Module.
"""

DEFAULT_INFRASTRUCTURE_INVESTMENT_COST = 500000 # MIGRATION: pennies (was 5000.0)
DEFAULT_ANNUAL_WEALTH_TAX_RATE = 0.02
DEFAULT_WEALTH_TAX_THRESHOLD = 5000000 # MIGRATION: pennies (was 50000.0)
DEFAULT_UNEMPLOYMENT_BENEFIT_RATIO = 0.8
DEFAULT_STIMULUS_TRIGGER_GDP_DROP = -0.05
DEFAULT_TICKS_PER_YEAR = 100
DEFAULT_HOUSEHOLD_FOOD_CONSUMPTION_PER_TICK = 1.0
DEFAULT_BASIC_FOOD_PRICE = 500 # MIGRATION: pennies (was 5.0)
