from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any, Union, Protocol, runtime_checkable
from simulation.ai.enums import PolicyActionTag
from modules.system.api import CurrencyCode
from modules.finance.api import BailoutLoanDTO

# region: Type Definitions
@runtime_checkable
class IAgent(Protocol):
    id: int

FirmID = int
HouseholdID = int
# endregion

# region: Existing DTOs
@dataclass
class TaxHistoryItemDTO:
    tick: int
    total: float
    tax_revenue: Dict[str, float]

@dataclass
class TaxBracketDTO:
    """Defines a single progressive tax bracket."""
    floor: float
    rate: float
    ceiling: Optional[float] # None for the highest bracket

@dataclass
class FiscalPolicyDTO:
    """State of the current fiscal policy."""
    progressive_tax_brackets: List[TaxBracketDTO]
    corporate_tax_rate: float = 0.2
    income_tax_rate: float = 0.1
    # TBD: Other fiscal tools like subsidies, welfare

@dataclass
class MonetaryPolicyDTO:
    """State of the current monetary policy."""
    target_interest_rate: float
    inflation_target: float
    unemployment_target: float
    # TBD: QE/QT parameters

@dataclass
class GovernmentStateDTO:
    """Immutable snapshot of the Government's state."""
    tick: int
    assets: Dict[str, float]
    total_debt: float
    income_tax_rate: float
    corporate_tax_rate: float
    fiscal_policy: 'FiscalPolicyDTO'
    ruling_party: Any # e.g., PoliticalParty Enum
    approval_rating: float
    policy_lockouts: Dict[Any, int] = field(default_factory=dict) # <PolicyActionTag, locked_until_tick>
    sensory_data: Optional['GovernmentSensoryDTO'] = None # Forward reference
    gdp_history: List[float] = field(default_factory=list)
    welfare_budget_multiplier: float = 1.0
    monetary_policy: Optional[MonetaryPolicyDTO] = None
    potential_gdp: float = 0.0
    fiscal_stance: float = 0.0

@dataclass
class PolicyDecisionDTO:
    """High-level strategic decision from the DecisionEngine."""
    action_tag: Any # e.g., PolicyActionTag Enum
    parameters: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)
    status: str = "OK"

@dataclass
class ExecutionResultDTO:
    """Concrete commands resulting from policy execution."""
    payment_requests: List['PaymentRequestDTO'] = field(default_factory=list)
    bailout_results: List['BailoutResultDTO'] = field(default_factory=list)
    monetary_ledger_updates: Dict[str, float] = field(default_factory=dict)
    state_updates: Dict[str, Any] = field(default_factory=dict) # For Orchestrator to update its state
    transactions: List[Any] = field(default_factory=list) # General transactions (e.g. from bailouts)
    executed_loans: List[Any] = field(default_factory=list) # Executed loan objects (e.g. from bailouts)

@dataclass
class MacroEconomicSnapshotDTO:
    """Snapshot of macro-economic indicators for Monetary Policy."""
    inflation_rate: float
    nominal_gdp: float
    potential_gdp: float
    unemployment_rate: float

@dataclass
class PolicyActionDTO:
    """Represents a proposed government policy action."""
    name: str
    utility: float
    tag: PolicyActionTag
    action_type: str
    params: Dict[str, Any] = field(default_factory=dict)
# endregion

# region: NEW & REVISED DTOs for Decoupling (TD-300)

@dataclass
class PaymentRequestDTO:
    """
    A stateless request for a financial transfer.
    Generated by a service, executed by the agent holding the wallet.
    """
    payer: Union[IAgent, FirmID, HouseholdID]
    payee: Union[IAgent, FirmID, HouseholdID]
    amount: float
    currency: CurrencyCode
    memo: str

@dataclass
class TaxCollectionResultDTO:
    """Result from a tax collection operation, containing payment requests."""
    payment_requests: List[PaymentRequestDTO] = field(default_factory=list)
    total_collected: float = 0.0
    tax_type: str = ""

@dataclass
class WelfareResultDTO:
    """Result from a welfare check operation, containing payment requests."""
    payment_requests: List[PaymentRequestDTO] = field(default_factory=list)
    total_paid: float = 0.0

@dataclass
class BailoutResultDTO:
    """
    Result from a bailout evaluation, requesting the creation of a loan
    and the initial fund transfer.
    """
    loan_request: BailoutLoanDTO # The DTO defining the loan terms
    payment_request: PaymentRequestDTO # The initial transfer of funds

# endregion
