from simulation.systems.api import ITransactionHandler, TransactionContext
from simulation.models import Transaction
from typing import Any

class DefaultTransferHandler(ITransactionHandler):
    """
    Handles generic 'transfer' transactions generated by SettlementSystem.
    These transactions are already financially settled by SettlementSystem.
    MonetaryLedger updates are now handled natively within SettlementSystem.transfer(),
    so this handler strictly acts as a pass-through to acknowledge the transaction
    without double-counting M2 metrics.
    """
    def handle(self, tx: Transaction, buyer: Any, seller: Any, context: TransactionContext) -> bool:
        # Transaction logic is already executed by SettlementSystem.
        # MonetaryLedger is already updated by SettlementSystem.transfer().
        # No further action needed to prevent Double-Counting Risk (WO-SSOT-INTENT).
        return True

    def rollback(self, tx: Transaction, context: TransactionContext) -> bool:
        """
        Default transfer handler is a pass-through for already settled transactions.
        Rollback is assumed to be handled by the caller or SettlementSystem directly.
        """
        return True
