from simulation.systems.api import ITransactionHandler, TransactionContext
from simulation.models import Transaction
from typing import Any

class DefaultTransferHandler(ITransactionHandler):
    """
    Handles generic 'transfer' transactions generated by SettlementSystem.
    These transactions are already financially settled; this handler
    serves strictly as a pass-through to ensure the MonetaryLedger
    can record the event for M2 Audits and tracking.
    """
    def handle(self, tx: Transaction, buyer: Any, seller: Any, context: TransactionContext) -> bool:
        # Transaction logic is already executed. Acknowledge for ledger.
        return True

    def rollback(self, tx: Transaction, context: TransactionContext) -> bool:
        """
        Default transfer handler is a pass-through for already settled transactions.
        Rollback is assumed to be handled by the caller or SettlementSystem directly.
        """
        return True
