"""
API contracts for the TaxationSystem and related data structures.
This API facilitates the decoupling of tax logic from the core TransactionProcessor.
"""
from __future__ import annotations
from typing import Protocol, List, TypedDict, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from simulation.models import Transaction
    from simulation.dtos.api import SimulationState

# ==================================================================
# Data Transfer Objects (DTOs)
# ==================================================================

class TaxIntentDTO(TypedDict):
    """
    A specific instruction for a tax payment, generated by the TaxationSystem.
    It includes the tax type for detailed revenue recording.
    """
    payer_id: int
    payee_id: int # Should always be the government's ID
    amount: float
    tax_type: str # e.g., "sales_tax", "income_tax", "wealth_tax"

class TaxCollectionResultDTO(TypedDict):
    """
    A record of the outcome of a tax collection attempt. This is used
    for asynchronous recording and auditing.
    """
    success: bool
    amount_collected: float
    tax_type: str
    payer_id: int
    payee_id: int
    tick: int
    error_message: Optional[str]

# ==================================================================
# System Interface
# ==================================================================

class ITaxationSystem(Protocol):
    """
    Defines the public interface for a system responsible for all tax-related
    calculations and record-keeping.
    """

    def generate_tax_intents(
        self,
        transaction: "Transaction",
        state: "SimulationState"
    ) -> List[TaxIntentDTO]:
        """
        Calculates all applicable taxes for a given transaction and returns them
        as a list of TaxIntentDTOs. This method is purely computational and
        MUST NOT cause any state changes.

        Args:
            transaction: The core transaction being processed (e.g., goods, labor).
            state: The current simulation state for context (e.g., market prices).

        Returns:
            A list of tax intents to be bundled into a settlement operation.
        """
        ...

    def record_revenue(self, intent: TaxIntentDTO, success: bool, tick: int) -> None:
        """
        Records the outcome of a tax payment attempt in the government's ledgers.
        This method is called by the orchestrator (TransactionProcessor) after
        the atomic settlement has been attempted.

        Args:
            intent: The original tax intent that was processed.
            success: A boolean indicating if the settlement was successful.
            tick: The current simulation tick.
        """
        ...
