from simulation.models import Transaction as Transaction
from simulation.systems.api import ITransactionHandler as ITransactionHandler, TransactionContext as TransactionContext
from typing import Any

class DefaultTransferHandler(ITransactionHandler):
    """
    Handles generic 'transfer' transactions generated by SettlementSystem.
    These transactions are already financially settled; this handler
    serves strictly as a pass-through to ensure the MonetaryLedger
    can record the event for M2 Audits and tracking.
    """
    def handle(self, tx: Transaction, buyer: Any, seller: Any, context: TransactionContext) -> bool: ...
