from _typeshed import Incomplete
from modules.finance.api import IFinancialAgent as IFinancialAgent, IFinancialEntity as IFinancialEntity
from modules.finance.transaction.api import IAccountAccessor as IAccountAccessor, ITransactionParticipant as ITransactionParticipant, ITransactionValidator as ITransactionValidator, InvalidAccountError as InvalidAccountError
from modules.system.api import CurrencyCode as CurrencyCode, DEFAULT_CURRENCY as DEFAULT_CURRENCY, IAgentRegistry as IAgentRegistry, ISystemFinancialAgent as ISystemFinancialAgent
from typing import Any

logger: Incomplete

class FinancialEntityAdapter:
    """
    Adapter for IFinancialEntity to ITransactionParticipant.
    """
    entity: Incomplete
    def __init__(self, entity: IFinancialEntity) -> None: ...
    def deposit(self, amount: int, currency: CurrencyCode = ..., memo: str = '') -> None: ...
    def withdraw(self, amount: int, currency: CurrencyCode = ..., memo: str = '') -> None: ...
    def get_balance(self, currency: CurrencyCode = ...) -> int: ...
    @property
    def allows_overdraft(self) -> bool: ...

class FinancialAgentAdapter:
    """
    Adapter for IFinancialAgent to ITransactionParticipant.
    """
    agent: Incomplete
    def __init__(self, agent: IFinancialAgent) -> None: ...
    def deposit(self, amount: int, currency: CurrencyCode = ..., memo: str = '') -> None: ...
    def withdraw(self, amount: int, currency: CurrencyCode = ..., memo: str = '') -> None: ...
    def get_balance(self, currency: CurrencyCode = ...) -> int: ...
    @property
    def allows_overdraft(self) -> bool: ...

class RegistryAccountAccessor(IAccountAccessor):
    registry: Incomplete
    def __init__(self, registry: IAgentRegistry) -> None: ...
    def get_participant(self, account_id: str) -> ITransactionParticipant: ...
    def exists(self, account_id: str) -> bool: ...

class DictionaryAccountAccessor(IAccountAccessor):
    """
    Accessor that uses a local dictionary of agents.
    Useful for testing or ad-hoc transactions where registry is not available.
    """
    agents_map: Incomplete
    def __init__(self, agents_map: dict[str, Any]) -> None: ...
    def get_participant(self, account_id: str) -> ITransactionParticipant: ...
    def exists(self, account_id: str) -> bool: ...
