from __future__ import annotations
from typing import TypedDict, List, Dict, Optional, Any

# --- DTOs for Market Stability Signals ---

class MarketSignalDTO(TypedDict):
    """
    Provides agents with essential, pre-calculated signals about a specific market's state.
    This is generated by the MarketSignalObserver after each trading round to ensure data purity
    for the next decision-making phase.
    """
    market_id: str
    item_id: str
    best_bid: Optional[float]
    best_ask: Optional[float]
    last_traded_price: Optional[float]
    price_history_7d: List[float]  # Rolling 7-tick price history
    volatility_7d: float  # Standard deviation of price_history_7d
    order_book_depth_buy: int  # Number of outstanding buy orders
    order_book_depth_sell: int  # Number of outstanding sell orders
    is_frozen: bool  # True if circuit breaker is active or no trades have occurred recently

# --- Modifications to Existing Core DTOs ---

class MarketSnapshotDTO(TypedDict):
    """
    [MODIFIED] A snapshot of all relevant market data for a given tick.
    This is a breaking change. The snapshot now contains a structured dictionary
    of market signals instead of raw, unstructured data.
    """
    tick: int
    market_signals: Dict[str, MarketSignalDTO]  # item_id -> signal_dto
    market_data: Dict[str, Any]  # [DEPRECATED] For legacy compatibility during transition.
