from __future__ import annotations
from dataclasses import dataclass, field
from typing import TypedDict, List, Dict, Optional, Any, Protocol

# --- DTOs for Market Stability Signals ---

@dataclass(frozen=True)
class MarketSignalDTO:
    """
    Provides agents with essential, pre-calculated signals about a specific market's state.
    This is generated by the MarketSignalObserver after each trading round to ensure data purity
    for the next decision-making phase.
    """
    market_id: str
    item_id: str
    best_bid: Optional[float]
    best_ask: Optional[float]
    last_traded_price: Optional[float]
    last_trade_tick: int  # Tick of the last trade
    price_history_7d: List[float]  # Rolling 7-tick price history
    volatility_7d: float  # Standard deviation of price_history_7d
    order_book_depth_buy: int  # Number of outstanding buy orders
    order_book_depth_sell: int  # Number of outstanding sell orders
    total_bid_quantity: float = 0.0 # Total quantity demanded
    total_ask_quantity: float = 0.0 # Total quantity supplied
    is_frozen: bool = False  # True if circuit breaker is active or no trades have occurred recently

# --- Comprehensive Market Snapshot DTOs ---

@dataclass(frozen=True)
class HousingMarketUnitDTO:
    """Represents a single, sellable housing unit in the market."""
    unit_id: str
    price: float
    quality: float
    rent_price: Optional[float] = None

@dataclass(frozen=True)
class HousingMarketSnapshotDTO:
    """Contains a snapshot of the housing market's state."""
    for_sale_units: List[HousingMarketUnitDTO]
    units_for_rent: List[HousingMarketUnitDTO]
    avg_rent_price: float
    avg_sale_price: float

@dataclass(frozen=True)
class LoanMarketSnapshotDTO:
    """Contains a snapshot of the loan market's state."""
    interest_rate: float

@dataclass(frozen=True)
class LaborMarketSnapshotDTO:
    """Contains a snapshot of the labor market's state."""
    avg_wage: float

@dataclass(frozen=True)
class MarketSnapshotDTO:
    """
    A comprehensive, read-only snapshot of all relevant market data for a given tick.
    Serves as the single source of truth for agent decision-making.
    """
    tick: int
    market_signals: Dict[str, MarketSignalDTO]  # item_id -> signal_dto

    # Domain-specific snapshots
    housing: Optional[HousingMarketSnapshotDTO] = None
    loan: Optional[LoanMarketSnapshotDTO] = None
    labor: Optional[LaborMarketSnapshotDTO] = None

    market_data: Dict[str, Any] = field(default_factory=dict)  # [DEPRECATED] For legacy compatibility during transition.

# --- Phase 3: Asset Recovery ---

class AgentBankruptcyEventDTO(TypedDict):
    """
    Broadcast when an agent fails. Contains details needed for asset recovery.
    """
    agent_id: int
    tick: int
    inventory: Dict[str, float]

class PublicManagerReportDTO(TypedDict):
    """
    Summarizes the Public Manager's activities.
    """
    tick: int
    newly_recovered_assets: Dict[str, float]
    liquidation_revenue: float
    managed_inventory_count: int
    system_treasury_balance: float

class IAssetRecoverySystem(Protocol):
    """
    Interface for the system service responsible for asset recovery and liquidation.
    """
    def process_bankruptcy_event(self, event: AgentBankruptcyEventDTO) -> None:
        """Takes ownership of a defunct agent's inventory."""
        ...

    def generate_liquidation_orders(self, market_signals: Dict[str, MarketSignalDTO]) -> List[Any]:
        """Generates non-disruptive SELL orders for managed assets."""
        # Note: Return type is List["Order"], using Any to avoid circular imports
        ...

    def deposit_revenue(self, amount: float) -> None:
        """Deposits revenue from liquidation sales into the system treasury."""
        ...

    def confirm_sale(self, item_id: str, quantity: float) -> None:
        """
        Confirms a sale transaction and permanently removes assets from inventory.
        Must be called by TransactionManager upon successful trade.
        """
        ...

    def get_status_report(self) -> PublicManagerReportDTO:
        """Returns a status report of the manager's state."""
        ...
