from _internal.registry.api import CommandContext as CommandContext, CommandResult, ICommand
from _typeshed import Incomplete
from pathlib import Path as Path

logger: Incomplete

class HarvestCommand(ICommand):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    def execute(self, ctx: CommandContext) -> CommandResult: ...

class SyncCommand(ICommand):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    def execute(self, ctx: CommandContext) -> CommandResult: ...

class ResetCommand(ICommand):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    def execute(self, ctx: CommandContext) -> CommandResult: ...
