from _internal.registry.api import CommandContext as CommandContext, CommandResult, ICommand
from _typeshed import Incomplete

logger: Incomplete

class GitReviewCommand(ICommand):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    def execute(self, ctx: CommandContext) -> CommandResult: ...

class MergeCommand(ICommand):
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    def execute(self, ctx: CommandContext) -> CommandResult: ...
