from modules.simulation.api import IBirthContext as IBirthContext, IDecisionEngine as IDecisionEngine, IFinanceTickContext as IFinanceTickContext
from modules.simulation.dtos.api import FirmConfigDTO, HouseholdConfigDTO
from modules.system.api import IAgentRegistry as IAgentRegistry
from simulation.core_agents import Household
from simulation.firms import Firm as Firm
from simulation.systems.settlement_system import FinancialSentry as FinancialSentry
from tests.utils.mocks import MockBirthContext as MockBirthContext, MockFinanceTickContext as MockFinanceTickContext

def create_household_config_dto(**kwargs) -> HouseholdConfigDTO: ...
def create_firm_config_dto(**kwargs) -> FirmConfigDTO: ...
def create_household(config_dto: HouseholdConfigDTO = None, id: int = 1, name: str = 'TestHousehold', assets: float = 1000.0, initial_needs: dict = None, value_orientation: str = 'needs_and_social_status', engine: IDecisionEngine | None = None, **kwargs) -> Household: ...
def create_firm(config_dto: FirmConfigDTO = None, id: int = 100, name: str = 'TestFirm', assets: float = 10000.0, specialization: str = 'food', productivity_factor: float = 1.0, initial_needs: dict = None, value_orientation: str = 'PROFIT', engine: IDecisionEngine | None = None, birth_context: IBirthContext | None = None, finance_context: IFinanceTickContext | None = None, **kwargs) -> Firm: ...
