from dataclasses import dataclass, field
from typing import Any

@dataclass
class ScenarioStrategy:
    """
    Unified Configuration DTO for Simulation Scenarios.
    Replaces StressScenarioConfig and eliminates global config pollution.
    """
    name: str = ...
    is_active: bool = ...
    start_tick: int = ...
    scenario_name: str | None = ...
    inflation_expectation_multiplier: float = ...
    hoarding_propensity_factor: float = ...
    demand_shock_cash_injection: float = ...
    panic_selling_enabled: bool = ...
    debt_aversion_multiplier: float = ...
    consumption_pessimism_factor: float = ...
    asset_shock_reduction: float = ...
    exogenous_productivity_shock: dict[str, float] = field(default_factory=dict)
    monetary_shock_target_rate: float | None = ...
    fiscal_shock_tax_rate: float | None = ...
    base_interest_rate_multiplier: float | None = ...
    corporate_tax_rate_delta: float | None = ...
    demand_shock_multiplier: float | None = ...
    tfp_multiplier: float = ...
    tech_fertilizer_unlock_tick: int = ...
    tech_diffusion_rate: float = ...
    food_sector_config: dict[str, Any] = field(default_factory=dict)
    market_config: dict[str, Any] = field(default_factory=dict)
    deflationary_pressure_multiplier: float = ...
    limits: dict[str, Any] = field(default_factory=dict)
    firm_decision_engine: str | None = ...
    household_decision_engine: str | None = ...
    initial_base_interest_rate: float | None = ...
    initial_corporate_tax_rate: float | None = ...
    initial_income_tax_rate: float | None = ...
    newborn_engine_type: str | None = ...
    firm_decision_mode: str | None = ...
    innovation_weight: float | None = ...
    parameters: dict[str, Any] = field(default_factory=dict)
