from dataclasses import dataclass, field

@dataclass
class FirmActionVector:
    """
    기업의 한 틱 행동을 정의하는 연속적 적극성 벡터.
    Values ideally range from 0.0 to 1.0.
    """
    sales_aggressiveness: float = ...
    hiring_aggressiveness: float = ...
    rd_aggressiveness: float = ...
    capital_aggressiveness: float = ...
    dividend_aggressiveness: float = ...
    debt_aggressiveness: float = ...

@dataclass
class HouseholdActionVector:
    """
    가계의 한 틱 행동을 정의하는 연속적 적극성 벡터.
    """
    consumption_aggressiveness: dict[str, float] = field(default_factory=dict)
    work_aggressiveness: float = ...
    job_mobility_aggressiveness: float = ...
    investment_aggressiveness: float = ...
    learning_aggressiveness: float = ...
