from modules.market.api import IIndexCircuitBreaker as IIndexCircuitBreaker, IPriceLimitEnforcer as IPriceLimitEnforcer
from modules.market.safety_dtos import PriceLimitConfigDTO as PriceLimitConfigDTO

class MarketSafetyPolicyManager:
    """
    Central registry for market safety policies.
    Allows dynamic updates to price limits and circuit breakers.
    """
    def __init__(self) -> None: ...
    def register_enforcer(self, market_id: str, enforcer: IPriceLimitEnforcer) -> None: ...
    def register_circuit_breaker(self, market_id: str, breaker: IIndexCircuitBreaker) -> None: ...
    def update_price_limit_config(self, market_id: str, config: PriceLimitConfigDTO) -> bool: ...
