from modules.household.dtos import BioStateDTO as BioStateDTO, EconStateDTO as EconStateDTO, SocialStateDTO as SocialStateDTO
from simulation.core_agents import Household as Household

class HouseholdStateContainer:
    """Helper to expose Household state components."""
    def __init__(self, agent: Household) -> None: ...
    @property
    def econ_state(self) -> EconStateDTO: ...
    @property
    def bio_state(self) -> BioStateDTO: ...
    @property
    def social_state(self) -> SocialStateDTO: ...
