from _typeshed import Incomplete
from modules.finance.api import IBank, IFinancialAgent, IFinancialEntity
from modules.system.api import AgentID as AgentID

class StrictMockBank(IBank):
    """
    A strict mock implementation of IBank without using MagicMock for everything,
    to ensure attributes are explicitly defined as per Protocol.
    """
    id: Incomplete
    base_rate: float
    def __init__(self, id: AgentID, balance: int = 0, deposits: int = 0) -> None: ...
    @property
    def balance_pennies(self) -> int: ...
    def deposit(self, amount_pennies: int, currency=...) -> None: ...
    def withdraw(self, amount_pennies: int, currency=...) -> None: ...
    def get_balance(self, currency=...) -> int: ...
    def get_all_balances(self): ...
    @property
    def total_wealth(self) -> int: ...
    def get_total_deposits(self) -> int: ...
    def grant_loan(self, *args, **kwargs) -> None: ...
    def stage_loan(self, *args, **kwargs) -> None: ...
    def repay_loan(self, loan_id: str, amount: int) -> int: ...
    def get_customer_balance(self, *args, **kwargs): ...
    def get_debt_status(self, *args, **kwargs) -> None: ...
    def terminate_loan(self, *args, **kwargs) -> None: ...
    def withdraw_for_customer(self, *args, **kwargs): ...
    def get_assets_by_currency(self, *args, **kwargs): ...
    def get_total_deposits_pennies(self) -> int: ...
    def close_account(self, agent_id) -> int: ...
    def receive_repayment(self, borrower_id, amount: int) -> int: ...
    def execute_open_market_operation(self, instruction): ...
    def process_omo_settlement(self, transaction) -> None: ...

class StrictFinancialAgent(IFinancialAgent, IFinancialEntity):
    id: Incomplete
    def __init__(self, id: AgentID, balance: int = 0) -> None: ...
    @property
    def balance_pennies(self) -> int: ...
    def deposit(self, amount_pennies: int, currency=...) -> None: ...
    def withdraw(self, amount_pennies: int, currency=...) -> None: ...
    def get_balance(self, currency=...) -> int: ...
    def get_all_balances(self): ...
    @property
    def total_wealth(self) -> int: ...

def test_audit_total_m2_strict_protocol() -> None:
    """
    Verifies that audit_total_m2 correctly calculates M2 using strict IBank protocol.
    """
def test_transfer_memo_validation() -> None:
    """
    Verifies that transfer handles memo validation (to be implemented).
    """
def test_transfer_invalid_agent() -> None:
    """
    Verifies transfer rejection for non-protocol agents.
    """
def test_mint_and_distribute_security():
    """
    Verifies minting security checks.
    """
def test_settle_atomic_logging() -> None:
    """
    Verifies settle_atomic logs failure properly.
    """
