from _typeshed import Incomplete
from dataclasses import replace as replace
from modules.common.config_manager.api import ConfigManager as ConfigManager
from modules.events.dtos import LoanDefaultedEvent as LoanDefaultedEvent
from modules.finance.api import BorrowerProfileDTO, DebtStatusDTO, IBank, IFinanceSystem as IFinanceSystem, IFinancialAgent as IFinancialAgent, IFinancialEntity, LoanDTO as LoanDTO
from modules.finance.wallet.api import IWallet as IWallet
from modules.simulation.api import AgentID
from modules.system.api import CurrencyCode as CurrencyCode, ICurrencyHolder
from modules.system.event_bus.api import IEventBus as IEventBus
from simulation.agents.government import Government as Government
from simulation.finance.api import ISettlementSystem as ISettlementSystem
from simulation.models import Transaction as Transaction
from typing import Any

logger: Incomplete

class Bank(IBank, ICurrencyHolder, IFinancialEntity):
    """
    Refactored Bank Agent (Stateless Wrapper).
    Delegates all financial logic to FinanceSystem (FinancialLedgerDTO).
    """
    config_manager: Incomplete
    settlement_system: Incomplete
    credit_scoring_service: Incomplete
    shareholder_registry: Incomplete
    event_bus: Incomplete
    government: Government | None
    finance_system: IFinanceSystem | None
    ticks_per_year: Incomplete
    base_rate: Incomplete
    current_tick_tracker: int
    value_orientation: str
    needs: dict[str, float]
    def __init__(self, id: AgentID, initial_assets: float, config_manager: ConfigManager, shareholder_registry: Any = None, settlement_system: ISettlementSystem | None = None, credit_scoring_service: Any = None, event_bus: IEventBus | None = None) -> None: ...
    @property
    def id(self) -> AgentID: ...
    @id.setter
    def id(self, value: AgentID): ...
    @property
    def wallet(self) -> IWallet: ...
    def set_finance_system(self, finance_system: IFinanceSystem) -> None: ...
    @property
    def balance_pennies(self) -> int: ...
    def deposit(self, amount_pennies: int, currency: CurrencyCode = ...) -> None: ...
    def withdraw(self, amount_pennies: int, currency: CurrencyCode = ...) -> None: ...
    def get_balance(self, currency: CurrencyCode = ...) -> int: ...
    def get_all_balances(self) -> dict[CurrencyCode, int]: ...
    @property
    def total_wealth(self) -> int: ...
    def get_liquid_assets(self, currency: CurrencyCode = 'USD') -> int: ...
    def get_total_debt(self) -> int: ...
    def get_assets_by_currency(self) -> dict[CurrencyCode, int]: ...
    def get_interest_rate(self) -> float: ...
    def set_government(self, government: Government) -> None: ...
    def update_base_rate(self, new_rate: float): ...
    def grant_loan(self, borrower_id: int, amount: int, interest_rate: float, due_tick: int = 0, borrower_profile: BorrowerProfileDTO | None = None) -> tuple[LoanDTO, Transaction] | None: ...
    def stage_loan(self, borrower_id: AgentID, amount: int, interest_rate: float, due_tick: int | None = None, borrower_profile: BorrowerProfileDTO | None = None) -> LoanDTO | None: ...
    def close_account(self, agent_id: AgentID) -> int: ...
    def repay_loan(self, loan_id: str, amount: int) -> int: ...
    def receive_repayment(self, borrower_id: AgentID, amount: int) -> int: ...
    def get_customer_balance(self, agent_id: AgentID) -> int: ...
    def get_debt_status(self, borrower_id: AgentID) -> DebtStatusDTO: ...
    def terminate_loan(self, loan_id: str) -> Transaction | None: ...
    def withdraw_for_customer(self, agent_id: AgentID, amount: int) -> bool: ...
    def get_total_deposits(self) -> int: ...
    def run_tick(self, agents_dict: dict[AgentID, Any], current_tick: int = 0) -> list[Transaction]: ...
    def deposit_from_customer(self, depositor_id: AgentID, amount: float, currency: CurrencyCode = ...) -> str | None: ...
