from _typeshed import Incomplete
from modules.demographics.genealogy.dtos import AncestorDTO as AncestorDTO, DescendantDTO as DescendantDTO, GenealogyTreeDTO as GenealogyTreeDTO
from modules.demographics.genealogy.service import GenealogyService as GenealogyService

def get_genealogy_service() -> GenealogyService: ...

router: Incomplete

def get_ancestors(agent_id: int, service: GenealogyService = ...): ...
def get_descendants(agent_id: int, service: GenealogyService = ...): ...
def get_tree(agent_id: int, depth: int = 3, service: GenealogyService = ...): ...
