import pytest
from typing import Any, Protocol

class IFirm(Protocol):
    id: int
    is_active: bool
    hr_state: Any
    capital_stock: float
    def get_all_items(self) -> dict[str, float]: ...
    def liquidate_assets(self, tick: int) -> dict[str, float]: ...
    def get_all_claims(self, context: Any) -> list[Any]: ...
    def get_equity_stakes(self, context: Any) -> list[Any]: ...

class IHousehold(Protocol):
    id: int
    is_active: bool
    def clear_inventory(self): ...

class TestDeathSystem:
    @pytest.fixture
    def death_system(self): ...
    def test_firm_liquidation(self, death_system) -> None: ...
    def test_firm_liquidation_cancels_orders(self, death_system) -> None: ...
    def test_death_system_emits_settlement_transactions(self, death_system) -> None: ...
