import pytest
from _typeshed import Incomplete
from modules.system.api import IAgentRegistry, IGlobalRegistry as IGlobalRegistry, IRestorableRegistry
from modules.system.constants import ID_CENTRAL_BANK as ID_CENTRAL_BANK
from simulation.dtos.commands import GodResponseDTO as GodResponseDTO
from simulation.finance.api import ISettlementSystem as ISettlementSystem
from unittest.mock import call as call
from uuid import uuid4 as uuid4

class MockRegistry(IRestorableRegistry):
    data: Incomplete
    def __init__(self) -> None: ...
    def get(self, key, default=None): ...
    def set(self, key, value, origin=None): ...
    def get_entry(self, key): ...
    def delete_entry(self, key): ...
    def restore_entry(self, key, entry): ...
    def lock(self, key) -> None: ...
    def unlock(self, key) -> None: ...
    def subscribe(self, observer, keys=None) -> None: ...
    def snapshot(self): ...
    def get_metadata(self, key): ...

class MockSettlementSystem:
    def audit_total_m2(self, expected_total=None): ...
    def mint_and_distribute(self, target_agent_id, amount, tick, reason): ...
    def transfer_and_destroy(self, source, sink_authority, amount, reason, tick, currency: str = 'USD'): ...
    def transfer(self, *args, **kwargs) -> None: ...
    def create_and_transfer(self, *args, **kwargs) -> None: ...
    def record_liquidation(self, *args, **kwargs) -> None: ...

class MockAgentRegistry(IAgentRegistry): ...

@pytest.fixture
def mock_registry(): ...
@pytest.fixture
def mock_settlement(): ...
@pytest.fixture
def mock_agent_registry(): ...
@pytest.fixture
def command_service(mock_registry, mock_settlement, mock_agent_registry): ...
def test_set_param_success(command_service, mock_registry) -> None: ...
def test_inject_asset_success(command_service, mock_settlement) -> None: ...
def test_audit_failure_rollback_money(command_service, mock_settlement, mock_agent_registry) -> None: ...
def test_mixed_batch_atomic_rollback(command_service, mock_registry, mock_settlement) -> None: ...
def test_validation_failure_aborts_batch(command_service, mock_registry) -> None: ...
