import pytest
from _typeshed import Incomplete
from modules.scenarios.api import ScenarioStrategy as ScenarioStrategy
from simulation.db.repository import SimulationRepository as SimulationRepository

logger: Incomplete
SCENARIO_DIR: Incomplete
SCENARIO_FILES: Incomplete

class MockRepository:
    """Mock repository to avoid DB overhead during tests."""
    runs: Incomplete
    agents: Incomplete
    markets: Incomplete
    metrics: Incomplete
    market_history: Incomplete
    analytics: Incomplete
    def __init__(self) -> None: ...
    def save_simulation_run(self, **kwargs): ...
    def update_simulation_run_end_time(self, run_id) -> None: ...
    def save_agent_states_batch(self, batch) -> None: ...
    def save_transactions_batch(self, batch) -> None: ...
    def save_economic_indicators_batch(self, batch) -> None: ...
    def save_market_history_batch(self, batch) -> None: ...
    def save_ai_decision(self, decision) -> None: ...
    def close(self) -> None: ...
    def migrate(self) -> None: ...

class ConfigWrapper:
    def __init__(self, base_config) -> None: ...
    def __getattr__(self, name): ...
    def set_override(self, name, value) -> None: ...

class TestScenarioRunner:
    @pytest.fixture
    def scenario_loader(self): ...
    @pytest.fixture
    def judge_factory(self): ...
    def create_population(self, config_module):
        """Creates households and firms based on config."""
    def test_run_scenario(self, scenario_file, scenario_loader, judge_factory) -> None: ...
