from dataclasses import dataclass, field
from modules.finance.api import BailoutLoanDTO as BailoutLoanDTO, BondDTO as BondDTO
from modules.system.api import CurrencyCode as CurrencyCode
from simulation.ai.enums import PolicyActionTag as PolicyActionTag
from typing import Any, Protocol

class IAgent(Protocol):
    id: int
FirmID = int
HouseholdID = int

@dataclass
class TaxHistoryItemDTO:
    tick: int
    total: int
    tax_revenue: dict[str, int]

@dataclass
class TaxBracketDTO:
    """Defines a single progressive tax bracket."""
    threshold: int
    rate: float
    floor: int = ...
    ceiling: int | None = ...

@dataclass(frozen=True)
class GovernmentPolicyDTO:
    """
    Unified Policy Snapshot for the Government.
    Consolidates Fiscal and Monetary stances for atomic state transfer.
    """
    tax_brackets: list[TaxBracketDTO] = field(default_factory=list)
    corporate_tax_rate: float = ...
    income_tax_rate: float = ...
    vat_rate: float = ...
    target_interest_rate: float = ...
    inflation_target: float = ...
    unemployment_target: float = ...
    welfare_budget_multiplier: float = ...
    bailout_threshold_solvency: float = ...
FiscalPolicyDTO = GovernmentPolicyDTO

@dataclass
class MonetaryPolicyDTO:
    """State of the current monetary policy."""
    target_interest_rate: float
    inflation_target: float
    unemployment_target: float

@dataclass
class GovernmentStateDTO:
    """Immutable snapshot of the Government's state."""
    tick: int
    assets: dict[str, int]
    total_debt: int
    income_tax_rate: float
    corporate_tax_rate: float
    policy: GovernmentPolicyDTO
    approval_rating: float
    fiscal_policy: FiscalPolicyDTO | None = ...
    policy_lockouts: dict[Any, int] = field(default_factory=dict)
    sensory_data: GovernmentSensoryDTO | None = ...
    gdp_history: list[float] = field(default_factory=list)
    welfare_budget_multiplier: float = ...
    potential_gdp: float = ...
    fiscal_stance: float = ...
    ruling_party: Any | None = ...

@dataclass
class PolicyDecisionDTO:
    """High-level strategic decision from the DecisionEngine."""
    action_tag: Any
    parameters: dict[str, Any] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)
    status: str = ...

@dataclass
class ExecutionResultDTO:
    """Concrete commands resulting from policy execution."""
    payment_requests: list['PaymentRequestDTO'] = field(default_factory=list)
    bailout_results: list['BailoutResultDTO'] = field(default_factory=list)
    monetary_ledger_updates: dict[str, int] = field(default_factory=dict)
    state_updates: dict[str, Any] = field(default_factory=dict)
    transactions: list[Any] = field(default_factory=list)
    executed_loans: list[Any] = field(default_factory=list)

@dataclass
class MacroEconomicSnapshotDTO:
    """Snapshot of macro-economic indicators for Monetary Policy."""
    inflation_rate: float
    nominal_gdp: float
    potential_gdp: float
    unemployment_rate: float

@dataclass
class PolicyActionDTO:
    """Represents a proposed government policy action."""
    name: str
    utility: float
    tag: PolicyActionTag
    action_type: str
    params: dict[str, Any] = field(default_factory=dict)

@dataclass
class FiscalContextDTO:
    """Context for fiscal operations (Tax, Bonds)."""
    tick: int
    current_gdp: int
    debt_to_gdp_ratio: float
    population_count: int
    treasury_balance: int

@dataclass
class BondIssueRequestDTO:
    """Request to issue bonds."""
    amount_pennies: int
    maturity_ticks: int
    target_yield: float

@dataclass
class PaymentRequestDTO:
    """
    A stateless request for a financial transfer.
    Generated by a service, executed by the agent holding the wallet.
    """
    payer: IAgent | FirmID | HouseholdID | str
    payee: IAgent | FirmID | HouseholdID | str
    amount: int
    currency: CurrencyCode
    memo: str

@dataclass
class BondIssuanceResultDTO:
    """Result of bond issuance preparation."""
    payment_request: PaymentRequestDTO
    bond_dto: BondDTO

@dataclass
class TaxAssessmentResultDTO:
    """Result from a tax assessment operation, containing payment requests."""
    payment_requests: list[PaymentRequestDTO] = field(default_factory=list)
    total_collected: int = ...
    tax_type: str = ...

@dataclass
class WelfareResultDTO:
    """Result from a welfare check operation, containing payment requests."""
    payment_requests: list[PaymentRequestDTO] = field(default_factory=list)
    total_paid: int = ...

@dataclass
class BailoutResultDTO:
    """
    Result from a bailout evaluation, requesting the creation of a loan
    and the initial fund transfer.
    """
    loan_request: BailoutLoanDTO
    payment_request: PaymentRequestDTO

@dataclass(frozen=True)
class BondRepaymentDetailsDTO:
    """
    A structured object carrying the details of a bond repayment.
    This DTO is expected to be present in the 'metadata' field of a 'bond_repayment' Transaction.

    Attributes:
        principal_pennies: The portion of the payment that constitutes principal repayment.
                           This amount is subject to monetary destruction if paid to the Central Bank.
        interest_pennies: The portion of the payment that constitutes an interest payment.
                          This is treated as a standard transfer and is not destroyed.
        bond_id: A unique identifier for the bond being serviced.
    """
    principal_pennies: int
    interest_pennies: int
    bond_id: str

@dataclass
class GovernmentSensoryDTO:
    """
    WO-057-B: Sensory Module DTO.
    Transfers 10-tick SMA macro data to the Government Agent.
    """
    tick: int
    inflation_sma: float
    unemployment_sma: float
    gdp_growth_sma: float
    wage_sma: float
    approval_sma: float
    current_gdp: float
    gini_index: float = ...
    approval_low_asset: float = ...
    approval_high_asset: float = ...
