from _typeshed import Incomplete

class DBManager:
    db_path: Incomplete
    conn: Incomplete
    cursor: Incomplete
    threshold: int
    def __init__(self, db_path: str = 'simulation_data.db') -> None: ...
    def flush(self) -> None:
        """
        Commits pending changes to the database.
        """
    def save_simulation_run(self, start_time, config_hash, description=None, buffered: bool = False): ...
    def update_simulation_run_end_time(self, run_id, end_time, buffered: bool = False) -> None: ...
    def save_simulation_state(self, run_id, tick, timestamp, global_economic_indicators, buffered: bool = True) -> None: ...
    def save_agent_state(self, run_id, tick, agent_id, agent_type, assets, inventory=None, needs=None, is_employed=None, employer_id=None, employees=None, production_targets=None, current_production=None, ai_model_state=None, buffered: bool = True) -> None: ...
    def save_transaction(self, run_id, tick, buyer_id, seller_id, item_id, quantity, price, transaction_type, loan_id=None, buffered: bool = True) -> None: ...
    def save_ai_decision(self, run_id, tick, agent_id, decision_type, decision_details=None, predicted_reward=None, actual_reward=None, buffered: bool = True) -> None: ...
    def get_simulation_run(self, run_id): ...
    def get_simulation_states(self, run_id, tick=None): ...
    def get_agent_states(self, run_id, tick=None, agent_id=None): ...
    def get_transactions(self, run_id, tick=None): ...
    def get_ai_decisions(self, run_id, tick=None, agent_id=None): ...
    def reset_database(self) -> None:
        """
        데이터베이스의 모든 테이블을 삭제하고 다시 생성하여 초기화합니다.
        """
    def close(self) -> None: ...
