from modules.common.config.api import StockMarketConfigDTO

stock_market_config = StockMarketConfigDTO(
    stock_market_enabled=True,
    stock_price_limit_rate=0.15,
    stock_transaction_fee_rate=0.001,
    ipo_initial_shares=1000.0,
    stock_price_method="book_value",
    stock_book_value_multiplier=1.0,
    stock_min_order_quantity=1.0,
    stock_order_expiry_ticks=5,
    seo_trigger_ratio=0.5,
    seo_max_sell_ratio=0.10,
    startup_min_capital=5000.0,
    startup_initial_shares=100.0,
    startup_probability=0.01,
    dividend_rate=0.1,
    dividend_rate_min=0.05,
    dividend_rate_max=0.5,
    bailout_repayment_ratio=0.5,
    friendly_merger_premium=1.1,
    hostile_takeover_premium=1.2,
    hostile_takeover_success_prob=0.6,
    merger_employee_retention_rates=(0.3, 0.5),
    ma_enabled=True,
    valuation_per_multiplier=10.0,
    min_acquisition_cash_ratio=1.5,
    liquidation_discount_rate=0.5,
    bankruptcy_consecutive_loss_ticks=20,
    bankruptcy_xp_penalty=0.2,
    credit_recovery_ticks=100,
    startup_cost=30000.0,
    startup_capital_multiplier=1.2,
    entrepreneurship_spirit=0.05
)
