from __future__ import annotations
from typing import List, TYPE_CHECKING, Any
import logging

if TYPE_CHECKING:
    from simulation.core_agents import Household
    from simulation.dtos.api import SimulationState
    from simulation.models import Transaction

from simulation.systems.api import AgentLifecycleManagerInterface
from simulation.systems.demographic_manager import DemographicManager
from simulation.systems.immigration_manager import ImmigrationManager
from simulation.systems.inheritance_manager import InheritanceManager
from simulation.systems.firm_management import FirmSystem
from simulation.ai.vectorized_planner import VectorizedHouseholdPlanner

class AgentLifecycleManager(AgentLifecycleManagerInterface):
    """
    Handles agent creation, aging, death, and liquidation.
    WO-103: Implements SystemInterface.
    WO-109: Returns transactions for deferred execution (Sacred Sequence).
    """

    def __init__(self, config_module: Any, demographic_manager: DemographicManager,
                 inheritance_manager: InheritanceManager, firm_system: FirmSystem, logger: logging.Logger):
        self.config = config_module
        self.demographic_manager = demographic_manager
        self.inheritance_manager = inheritance_manager
        self.firm_system = firm_system
        self.immigration_manager = ImmigrationManager(config_module=config_module)
        self.breeding_planner = VectorizedHouseholdPlanner(config_module)
        self.logger = logger

    def execute(self, state: SimulationState) -> List[Transaction]:
        """
        Processes lifecycle events for the tick.
        Returns:
            List[Transaction]: Transactions generated by lifecycle events (e.g., inheritance)
                               to be queued for the NEXT tick.
        """
        # 1. Aging (and internal lifecycle update)
        self.demographic_manager.process_aging(state.households, state.time, state.market_data)

        # 2. NEW: Firm Lifecycle (Aging & Bankruptcy Checks)
        self._process_firm_lifecycle(state)

        # 3. Births
        new_children = self._process_births(state)
        self._register_new_agents(state, new_children)

        # 4. Immigration
        new_immigrants = self.immigration_manager.process_immigration(state)
        self._register_new_agents(state, new_immigrants)

        # 5. Entrepreneurship
        self.firm_system.check_entrepreneurship(state)

        # 6. Death & Liquidation
        return self._handle_agent_liquidation(state)

    def _process_firm_lifecycle(self, state: SimulationState) -> None:
        """
        Handles lifecycle updates for all active firms, formerly in Firm.update_needs.
        """
        assets_threshold = getattr(self.config, "ASSETS_CLOSURE_THRESHOLD", 0.0)
        closure_turns_threshold = getattr(self.config, "FIRM_CLOSURE_TURNS_THRESHOLD", 5)
        liquidity_inc_rate = getattr(self.config, "LIQUIDITY_NEED_INCREASE_RATE", 1.0)

        for firm in state.firms:
            if not firm.is_active:
                continue

            firm.age += 1

            # Liquidity Need Increase
            firm.needs["liquidity_need"] = min(100.0, firm.needs["liquidity_need"] + liquidity_inc_rate)

            # Check bankruptcy status (logic from FinanceDepartment)
            firm.finance.check_bankruptcy()

            # Check for closure based on assets or consecutive losses
            if (firm.assets <= assets_threshold or
                    firm.finance.consecutive_loss_turns >= closure_turns_threshold):
                firm.is_active = False
                self.logger.warning(
                    f"FIRM_INACTIVE | Firm {firm.id} closed down. Assets: {firm.assets:.2f}, Consecutive Loss Turns: {firm.finance.consecutive_loss_turns}",
                    extra={
                        "tick": state.time,
                        "agent_id": firm.id,
                        "assets": firm.assets,
                        "consecutive_loss_turns": firm.finance.consecutive_loss_turns,
                        "tags": ["firm_closure"],
                    }
                )

    def _process_births(self, state: SimulationState) -> List[Household]:
        birth_requests = []
        active_households = [h for h in state.households if h.is_active]
        if not active_households:
            return []

        decisions = self.breeding_planner.decide_breeding_batch(active_households)
        for h, decision in zip(active_households, decisions):
            if decision:
                birth_requests.append(h)

        return self.demographic_manager.process_births(state, birth_requests)

    def _register_new_agents(self, state: SimulationState, new_agents: List[Household]):
        for agent in new_agents:
            state.households.append(agent)
            state.agents[agent.id] = agent
            agent.decision_engine.markets = state.markets
            agent.decision_engine.goods_data = state.goods_data

            if state.stock_market:
                for firm_id, qty in agent.shares_owned.items():
                    state.stock_market.update_shareholder(agent.id, firm_id, qty)

            if state.ai_training_manager:
                state.ai_training_manager.agents.append(agent)

    def _calculate_inventory_value(self, inventory: dict, markets: dict) -> float:
        total_value = 0.0
        default_price = getattr(self.config, "GOODS_INITIAL_PRICE", {}).get("default", 10.0)

        for item_id, qty in inventory.items():
            price = default_price
            if item_id in markets:
                m = markets[item_id]
                if hasattr(m, "avg_price") and m.avg_price > 0:
                    price = m.avg_price
                elif hasattr(m, "current_price") and m.current_price > 0:
                    price = m.current_price

            total_value += qty * price
        return total_value

    def _handle_agent_liquidation(self, state: SimulationState) -> List[Transaction]:
        """
        Handles liquidation of inactive firms and households.
        Returns a list of transactions (specifically from Inheritance).
        """
        transactions: List[Transaction] = []

        # --- Firm Liquidation ---
        # Note: Firm liquidation currently uses direct SettlementSystem transfers.
        # Ideally this should also be transaction-based, but for TD-109 we focus on Inheritance.
        inactive_firms = [f for f in state.firms if not f.is_active]
        for firm in inactive_firms:
            self.logger.info(
                f"FIRM_LIQUIDATION | Starting liquidation for Firm {firm.id}.",
                extra={"agent_id": firm.id, "tags": ["liquidation"]}
            )

            if state.reflux_system:
                inv_value = self._calculate_inventory_value(firm.inventory, state.markets)
                if inv_value > 0:
                    state.reflux_system.capture(inv_value, str(firm.id), "liquidation_inventory")
                    if hasattr(state.government, "total_money_issued"):
                        # firm._add_assets(inv_value) # Removed to prevent Double Creation (Reflux has it)
                        state.government.total_money_issued += inv_value

                if firm.capital_stock > 0:
                    state.reflux_system.capture(firm.capital_stock, str(firm.id), "liquidation_capital")
                    if hasattr(state.government, "total_money_issued"):
                        # firm._add_assets(firm.capital_stock) # Removed to prevent Double Creation
                        state.government.total_money_issued += firm.capital_stock

            # Clear employees
            for employee in firm.hr.employees:
                if employee.is_active:
                    employee.is_employed = False
                    employee.employer_id = None
            firm.hr.employees = []
            firm.inventory.clear()
            firm.capital_stock = 0.0

            # Distribute cash
            total_cash = firm.assets
            if total_cash > 0:
                outstanding_shares = firm.total_shares - firm.treasury_shares
                if outstanding_shares > 0:
                    shareholders = list(state.households)
                    if hasattr(state, 'government') and state.government:
                        shareholders.append(state.government)

                    for agent in shareholders:
                        shares = 0
                        if hasattr(agent, "shares_owned"):
                            shares = agent.shares_owned.get(firm.id, 0)

                        if shares > 0:
                            share_ratio = shares / outstanding_shares
                            distribution = total_cash * share_ratio
                            if hasattr(state, "settlement_system") and state.settlement_system:
                                state.settlement_system.transfer(firm, agent, distribution, "liquidation_dividend")

                else:
                    if hasattr(state, "government") and state.government:
                        # Atomic Collection via Government (handles transfer and revenue recording)
                        state.government.collect_tax(total_cash, "liquidation_escheatment", firm, state.time)

            # Verification: Firm assets should be ~0 now
            if firm.assets > 1e-6:
                 firm._sub_assets(firm.assets)
                 if hasattr(state.government, "total_money_destroyed"):
                     state.government.total_money_destroyed += firm.assets

            # Clear shareholdings
            for household in state.households:
                if firm.id in household.shares_owned:
                    del household.shares_owned[firm.id]
                    if state.stock_market:
                        state.stock_market.update_shareholder(household.id, firm.id, 0)

        # --- Household Liquidation (Inheritance) ---
        inactive_households = [h for h in state.households if not h.is_active]
        for household in inactive_households:
            # WO-109: Preserve inactive agent for transaction processing
            if hasattr(state, "inactive_agents") and isinstance(state.inactive_agents, dict):
                state.inactive_agents[household.id] = household

            # Capture transactions returned by InheritanceManager
            inheritance_txs = self.inheritance_manager.process_death(household, state.government, state)
            transactions.extend(inheritance_txs)

            if state.reflux_system:
                inv_value = self._calculate_inventory_value(household.inventory, state.markets)
                if inv_value > 0:
                    state.reflux_system.capture(inv_value, str(household.id), "liquidation_inventory")
                    if hasattr(state.government, "total_money_issued"):
                        # state.government._add_assets(inv_value) # Removed to prevent Double Creation
                        state.government.total_money_issued += inv_value

            household.inventory.clear()
            household.shares_owned.clear()
            if hasattr(household, "portfolio"):
                 household.portfolio.holdings.clear()
            if state.stock_market:
                for firm_id in list(state.stock_market.shareholders.keys()):
                     state.stock_market.update_shareholder(household.id, firm_id, 0)

        # Cleanup Global Lists
        state.households[:] = [h for h in state.households if h.is_active]
        state.firms[:] = [f for f in state.firms if f.is_active]

        state.agents.clear()
        state.agents.update({agent.id: agent for agent in state.households + state.firms})
        if state.bank:
             state.agents[state.bank.id] = state.bank
        if hasattr(state, 'government') and state.government:
             state.agents[state.government.id] = state.government
        if hasattr(state, 'central_bank') and state.central_bank:
             state.agents[state.central_bank.id] = state.central_bank

        for firm in state.firms:
            firm.hr.employees = [
                emp for emp in firm.hr.employees if emp.is_active and emp.id in state.agents
            ]

        return transactions
