from modules.finance.api import IFinancialAgent as IFinancialAgent, InsufficientFundsError as InsufficientFundsError
from modules.system.api import CurrencyCode as CurrencyCode, DEFAULT_CURRENCY as DEFAULT_CURRENCY

class EscrowAgent(IFinancialAgent):
    """
    Acts as a temporary holding account for atomic transactions.
    Ensures funds are secured before distribution to sellers and government.
    """
    def __init__(self, id: int) -> None: ...
    @property
    def id(self) -> int: ...
    def get_balance(self, currency: CurrencyCode = ...) -> int: ...
    def get_all_balances(self) -> dict[CurrencyCode, int]: ...
    @property
    def total_wealth(self) -> int: ...
    @property
    def balance_pennies(self) -> int: ...
    def deposit(self, amount_pennies: int, currency: CurrencyCode = ...) -> None: ...
    def withdraw(self, amount_pennies: int, currency: CurrencyCode = ...) -> None: ...
    def get_liquid_assets(self, currency: CurrencyCode = ...) -> int: ...
    def get_total_debt(self) -> int: ...
