import pytest

@pytest.fixture
def saga_orchestrator(): ...
def test_submit_saga(saga_orchestrator) -> None: ...
def test_process_sagas_liveness_check(saga_orchestrator) -> None: ...
def test_process_sagas_active_participants(saga_orchestrator) -> None: ...
def test_find_and_compensate_by_agent_success(saga_orchestrator) -> None: ...
def test_find_and_compensate_by_agent_no_handler(saga_orchestrator) -> None: ...
