import pytest
from _typeshed import Incomplete
from modules.finance.api import IFinancialAgent as IFinancialAgent, IFinancialEntity as IFinancialEntity
from modules.system.api import IAgentRegistry as IAgentRegistry
from simulation.models import Order as Order
from typing import Any
from unittest.mock import Mock as Mock

class OMOTestAgent:
    id: Incomplete
    total_money_issued: int
    total_money_destroyed: int
    monetary_ledger: Incomplete
    def __init__(self, agent_id, assets: int = 0) -> None: ...
    @property
    def balance_pennies(self) -> int: ...
    def deposit(self, amount: int, currency=...): ...
    def withdraw(self, amount: int, currency=...): ...
    def get_balance(self, currency=...) -> int: ...
    def get_all_balances(self) -> dict[str, int]: ...
    @property
    def total_wealth(self) -> int: ...
    def get_liquid_assets(self, currency: str = 'USD') -> float: ...
    def get_total_debt(self) -> float: ...
    def execute_open_market_operation(self, instruction): ...
    def process_omo_settlement(self, transaction) -> None: ...

class MockRegistry:
    agents: Incomplete
    def __init__(self, agents: list[Any]) -> None: ...
    def get_agent(self, agent_id: Any) -> Any: ...
    def get_all_financial_agents(self) -> list[Any]: ...
    def set_state(self, state: Any) -> None: ...

@pytest.fixture
def omo_setup(): ...
def test_execute_omo_purchase_order_creation(omo_setup) -> None: ...
def test_execute_omo_sale_order_creation(omo_setup) -> None: ...
def test_process_omo_purchase_transaction(omo_setup) -> None: ...
def test_process_omo_sale_transaction(omo_setup) -> None: ...
